############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Courses"
url = "courses/"
weight = 2

[[main]]
name = "Tools"
url = "tools/"
weight = 3

[[main]]
name = "Pages"
url = "#"
weight = 4
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Tags"
  url = "tags/"
  weight = 1

  [[main]]
  parent = "Pages"
  name = "Categories"
  url = "categories/"
  weight = 2

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4
